package com.samprakash.basemodel;

public enum Status {

	NOT_APPLICAPLE,SUCCESS,FAILURE,CURRENT_PASSWORD_MISMATCHED,OLD_PASSWORD_REUSED,
	EMAIL_ID_ALREADY_USED,CONTACT_NO_ALREADY_USED,EMPTY_CHANGES,ALREADY_EXIST
}
