package com.samprakash.ticketbookmodel;

public enum BookingState {

	USER_NAME,BOOKING_MOBILE_NO,BOOKING_EMAIL_ID, TRAIN_ID, TRAIN_NAME,CLASS_TYPE, PNR_NUMBER, TRAVEL_DATE, SOURCE, DESTINATION, TRANSACTION_ID, TOTAL_TICKET_FARE,
	BOOKING_STATUS, TRANSACTION_STATUS,ASSOCIATED_PASSENGER
}
